### ISSUE TITLE
Eclipse killed while debugging by JDT LS

### ISSUE THREAD

**Issue by akurtakov** [redhat-developer/eclipseide-jdtls#24]
If one prolongs debugging too long so JDT LS tries to shutdown itself it ends up calling https://github.com/eclipse/eclipse.jdt.ls/blob/bf2c9865a1fef1870a58a5ccc62eb686ce8d639c/org.eclipse.jdt.ls.core/src/org/eclipse/jdt/ls/core/internal/handlers/JDTLanguageServer.java#L450 and thus bringing the whole IDE down.

**Comment by mickaelistria** [comment]
See https://github.com/eclipse/eclipse.jdt.ls/pull/2499 which should prevent this issue from happening.

**Comment by mickaelistria** [comment]
This should now be fixed
