### ISSUE TITLE
.settings/o.e.jdt.core.prefs and other files modified

### ISSUE THREAD

**Issue by akurtakov** [redhat-developer/eclipseide-jdtls#41]
E.g. .project files get the following added to them:
```
	<filteredResources>
		<filter>
			<id>1676382308269</id>
			<name></name>
			<type>30</type>
			<matcher>
				<id>org.eclipse.core.resources.regexFilterMatcher</id>
				<arguments>node_modules|\.git|__CREATED_BY_JAVA_LANGUAGE_SERVER__</arguments>
			</matcher>
		</filter>
	</filteredResources>
```

**Comment by mickaelistria** [comment]
I opened https://github.com/eclipse/eclipse.jdt.ls/issues/2562

**Comment by rgrunber** [comment]
Looking at https://github.com/redhat-developer/eclipseide-jdtls/pull/15 there was a workaround for this. Is it no longer working ?

**Comment by mickaelistria** [comment]
I believe the implementation in #15 is not always fully working. Could it be that configureFilters could sometimes be called before LS initializationOptions are received?

**Comment by mickaelistria** [comment]
and patch #15 only considers filters, not settings. However, I still strongly believe that the LS should just respect user defined settings when pre-existing and not override them automatically.

**Comment by mickaelistria** [comment]
I couldn't reproduce the issue lately. Maybe there was some JDT issue happening as well. Let's close for the moment.
