### ISSUE TITLE
Hover helps has 2 "Press F2 to focus" footers

### ISSUE THREAD

**Issue by akurtakov** [redhat-developer/eclipseide-jdtls#42]
![image](https://user-images.githubusercontent.com/574788/228259680-05fabc6f-8758-4634-9eed-3b3a830d3ae2.png)

It might be trivial but at least it's suspicious.

**Comment by mickaelistria** [comment]
Proposed fix in Platform Generic Editor: https://github.com/eclipse-platform/eclipse.platform.text/pull/195
