### ISSUE TITLE
Syntax hightlighting incorrect for import statements

### ISSUE THREAD

**Issue by vogella** [redhat-developer/eclipseide-jdtls#56]
Using latest from https://redhat-developer.github.io/eclipseide-jdtls and opening StackRendererTest from eclipse.platform.ui

The "Inject" is incorrect highlighted.

![image](https://user-images.githubusercontent.com/139910/232723025-f57e3256-0cb6-4b91-925f-7c2d42ffa4c4.png)

**Comment by mickaelistria** [comment]
The same issue can be reproduced with vscode-java; so I suspect it's coming from the implementation of `semanticTokens` in JDT-LS. Would you mind opening an issue there?

**Comment by vogella** [comment]
Done
