### ISSUE TITLE
Lots of meaningless >> document/codeAction  output

### ISSUE THREAD

**Issue by vogella** [redhat-developer/eclipseide-jdtls#57]
If I try to use this tooling I see around 30 message of >> document/codeAction without any details.

This seems not valuable for me as user

![image](https://user-images.githubusercontent.com/139910/232724039-86635c5e-1129-488a-a36a-6b0258ff61eb.png)

![image](https://user-images.githubusercontent.com/139910/232724084-6c45b237-e556-4407-bdf4-e7bd2b805b25.png)

**Comment by mickaelistria** [comment]
I reported https://github.com/eclipse/eclipse.jdt.ls/issues/2603

**Comment by mickaelistria** [comment]
There are now way less output.
