### ISSUE TITLE
Error in updating the project after restart

### ISSUE THREAD

**Issue by vogella** [redhat-developer/eclipseide-jdtls#60]
After installing this tooling I get lots of errors after a restart:

![image](https://user-images.githubusercontent.com/139910/232731493-c37023d5-9898-4549-a5ef-f8f792777596.png)

Error message for one project

Error updating org.eclipse.ui.monitoring.tests
Exception updating digest for /home/vogella/git/eclipse.platform.ui/tests/org.eclipse.ui.monitoring.tests/pom.xml
/home/vogella/git/eclipse.platform.ui/tests/org.eclipse.ui.monitoring.tests/pom.xml

Git shows me that the .project file have been edited which might or might not be OK but an error and especially a error popup is not desired.

````
	<filteredResources>
		<filter>
			<id>1676382308261</id>
			<name></name>
			<type>30</type>
			<matcher>
				<id>org.eclipse.core.resources.regexFilterMatcher</id>
				<arguments>node_modules|\.git|__CREATED_BY_JAVA_LANGUAGE_SERVER__</arguments>
			</matcher>
		</filter>
	</filteredResources>

````

**Comment by mickaelistria** [comment]
Seems related to #41 ; but the oddity here is that we already have enabled a flag that should disable edition of .project; it looks like this flag is not functioning in some cases. Can you please check the artifact version ?
Do you have a stacktrace or minimal steps to reproduce this issue? I do not see it on my end.

**Comment by vogella** [comment]
It seems to have happend after the installation into an existing workspace.

**Comment by akurtakov** [comment]
Do you still face this issue?

**Comment by mickaelistria** [comment]
Seems like this hasn't happened for a while. Let's close.

**Comment by vogella** [comment]
Sorry for  not being responsive, I did not re-install it so far due to lack of time.
