### ISSUE TITLE
Support save actions 

### ISSUE THREAD

**Issue by akurtakov** [redhat-developer/eclipseide-jdtls#79]
## Suggestion

JDT.UI has a notion of "save action" - performing code manipulation on save (e.g. "organize imports"). JDT LS also supports this and it's exposed in [VScode Java](https://github.com/redhat-developer/vscode-java/blob/master/document/_java.learnMoreAboutCleanUps.md) .
JDT LS and JDT UI implementations use different keys for same save actions. As for both the keys are part of user configs it's not feasible to change any of them thus the plan is:
* Make JDT LS support both keys for same actions
* Feed JDT LS with org.eclipse.jdt.ui.prefs from the project to enable the execution of the save action.

## Community

- [x] I understand suggesting an enhancement doesn't mandate anyone to implement it. Other contributors may consider this suggestion, or not, at their own convenience. The most efficient way to get it fixed is that I implement it myself and contribute it back as a good quality patch to the project.

**Comment by akurtakov** [comment]
@mickaelistria Is it feasible to have different org.eclipse.jdt.ui.prefs per project while using same JDT LS process ?

**Comment by mickaelistria** [comment]
I'm not sure I get the question ;)

>  different org.eclipse.jdt.ui.prefs per project

You mean each project would have its own org.eclipse.jdt.ui.prefs? If yes, then yes, it's totally possible.
If you want 1 project to have multiple org.eclipse.jdt.ui.prefs and some consumers automatically picking one or the other under some criterion, it's way less possible. If there is one which is dedicated to JDT-LS, it would be easier to have a org.eclipse.jdt.ls.prefs file that JDT-LS would use (possibly chaining it with the org.eclipse.jdt.ui.prefs one as fail-back).

**Comment by mickaelistria** [comment]
Fixed upstream with https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2870 and verified in latest snapshot. Note that if it takes more that 3 seconds for the LS to compute the save actions, they are discarded.
