### ISSUE TITLE
Fold import statements by default

### ISSUE THREAD

**Issue by akurtakov** [redhat-developer/eclipseide-jdtls#88]
## Suggestion

Import statements are not the first thing one wants to read in java file thus it makes sense to open files with these folded. VSCode can do that if *editor.foldingImportsByDefault* is enabled. 
JDT-LS returns a list of folding ranges that can have a kind of "comment" or "imports" or "region" so folding "imports" when opening editor makes perfect sense to me.

## Community

- [x] I understand suggesting an enhancement doesn't mandate anyone to implement it. Other contributors may consider this suggestion, or not, at their own convenience. The most efficient way to get it fixed is that I implement it myself and contribute it back as a good quality patch to the project.

**Comment by mickaelistria** [comment]
Fixed in LSP4E: https://github.com/eclipse/lsp4e/commit/3cc5a5f53fd0c365b4800b82499c3b85818aee80
